Fc 469 initiate recruit from my preferences page
SkillsFundingAgency/das-employer-favourites pull request #44
Opened 2019-10-08 09:03 UTC by ben1stone

First commit contains the bulk of the work and unit tests and the second contains the integration tests.

2019-10-08 12:35 UTC, leewadhams requested changes
Looks good. A few tidy up things to be done/considered.

2019-10-08 12:35 UTC, leewadhams commented on src/web/EmployerFavouritesWeb/Application/Queries/EmployerHasLegalEntityQuery.cs
> +﻿
Blank line

2019-10-08 12:35 UTC, leewadhams commented on src/web/EmployerFavouritesWeb/Application/Queries/EmployerHasLegalEntityQueryHandler.cs
> +using DfE.EmployerFavourites.Domain;
Unused using

2019-10-08 12:35 UTC, leewadhams commented on src/web/EmployerFavouritesWeb/Application/Queries/EmployerHasLegalEntityQueryHandler.cs
> +        }
Space between methods

2019-10-08 12:35 UTC, leewadhams commented on src/web/EmployerFavouritesWeb/Application/Queries/EmployerHasLegalEntityQueryHandler.cs
> +            catch (System.Exception e)
Would normally have a `using System` statement at the top of the file.

2019-10-08 12:35 UTC, leewadhams commented on src/web/EmployerFavouritesWeb/Configuration/ExternalLinks.cs
> +        public string RecruitFromProgramme { get; set; }
I think maybe they could be named to make it clearer what they're for. Maybe `CreateVacancyForProgramme` & `CreateVacancyForProgrammeAndProvider`.

What do you think?

Are they 2 separate urls in any case? or is it a single url that has optional query string parameters?

2019-10-08 12:35 UTC, leewadhams commented on src/web/EmployerFavouritesWeb/Controllers/ApprenticeshipsController.cs
> +            var employerHasLegalEntityResponse = await _mediator.Send(new EmployerHasLegalEntityQuery
I'm wondering if we should do this in the controller of whether it should be part of the other query.

2019-10-08 12:35 UTC, leewadhams commented on src/web/EmployerFavouritesWeb/Models/ApprenticeshipFavouritesViewModel.cs
> +        public string ProgrammeUrl { get; set; }
CreateVacancyUrl?

2019-10-08 12:35 UTC, leewadhams commented on src/web/EmployerFavouritesWeb/Models/TrainingProvidersViewModel.cs
> +        public string ProgrammeAndProviderUrl { get; set; }
CreateVacancyUrl?

2019-10-08 12:35 UTC, leewadhams commented on src/web/EmployerFavouritesWeb/Views/Apprenticeships/TrainingProvider.cshtml
> +                                <a href="@string.Format(Model.ProgrammeAndProviderUrl,Model.EmployerAccountId,Model.Items[i].Ukprn,Model.ApprenticeshipId)" class="govuk-button app-task-list__training
I'd be tempted to have the generated url as a property on the view model.

2019-10-08 12:35 UTC, leewadhams commented on src/web/IntegrationTests/Stubs/StubAccountApiClient.cs
> +                        Href = "/api/accounts/XXX321/legalentities/654321"
Don't know if it's confusing having different account ids in each of the urls.

2019-10-08 12:35 UTC, leewadhams commented on src/web/IntegrationTests/appSettings.json
> +    "RecruitFromProgramme": "https://recruit.at-eas.apprenticeships.education.gov.uk/accounts/{0}/employer-create-vacancy?ProgrammeId={1}",
Yeah I think we can probably just have a single url

2019-10-08 15:54 UTC, ben1stone-leftdfe commented on src/web/EmployerFavouritesWeb/Controllers/ApprenticeshipsController.cs
> +            var employerHasLegalEntityResponse = await _mediator.Send(new EmployerHasLegalEntityQuery
I've finished all the other changes. Just this one left to do. I did consider it but it would need to be implemented into two slightly different queries one for Favourites and then again for the Providers when you go into each favourite.

2019-10-08 15:55 UTC, ben1stone-leftdfe commented on src/web/EmployerFavouritesWeb/Controllers/ApprenticeshipsController.cs
> +            var employerHasLegalEntityResponse = await _mediator.Send(new EmployerHasLegalEntityQuery
@leewadhams see above.

2019-10-21 09:28 UTC, leewadhams approved these changes

2019-10-21 09:28 UTC, leewadhams commented on src/api/IntegrationTests/IntegrationTests.csproj
> +    <UserSecretsId>e4b53c92-d5f5-45a6-9912-353d3945751a</UserSecretsId>
Don't think this is needed for this project.

2019-11-05 12:15 UTC, sultansfa1 approved these changes
This has been tested and ready for release

2019-11-06 13:08 UTC, merged