Fc 947 delete campaign shortlist once govuk account is created
SkillsFundingAgency/das-employer-favourites pull request #59
Opened 2019-12-11 15:07 UTC by ben1stone

Adds new method from the shared basket to delete the favourites basket once it has been saved into the favourites app.

2019-12-12 14:41 UTC, desderry requested changes

2019-12-12 14:41 UTC, desderry commented on src/web/IntegrationTests/Stubs/StubFavouritesBasketStore.cs
> +            throw new NotImplementedException();
This will need an implementation and should be tested as part of the Application/Commands/SaveApprenticeshipFavouriteBasketCommandHandler.cs tests

2019-12-17 11:26 UTC, desderry approved these changes

2020-01-09 10:06 UTC, sultansfa1 approved these changes
I have tested this successfully.

2020-01-15 09:30 UTC, merged